name: PR - Tests & SonarQube

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PR Tests & SonarQube
        uses: llNABSll/pull-request-action@main
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          UNIT_TESTS_COMMAND: coverage run --source=dev/src -m behave dev/tests/features --junit --junit-directory reports; coverage xml -o coverage.xml
          REPORT_PATH: '**/reports/TESTS-*.xml'