name: PR - Tests & SonarQube

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          coverage run --source=dev/src -m behave dev/tests/features
          coverage xml -o coverage.xml

      - name: Publish Test Report
        # uses: mikepenz/action-junit-report@v5
        # if: success() || failure()
        # with:
        #   report_paths: '**/reports/TESTS-*.xml'
        uses: EnricoMi/publish-unit-test-result-action@v2.20.0
        with:
          files: '**/TESTS-*.xml'


      - name: publish coverage report
        uses: 5monkeys/cobertura-action@v14
        with:
          minimum_coverage: 75

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
